"""``trialerror program`` — the per-program scaffold bootstrap. Design Section
3.2's worked example (``trialerror program init <name> --dir <path>``) + Section
5.2's CLI table row: ``program | init, list, info | scaffold + config``.

FX-16 / FX-10 (IMPL_REVIEW_VERDICT.md Tier 2 + the docs-pass addition,
NB-2/SD-2 in ``docs/reviews/IMPL_REVIEW_A_spec.md``): no lane ever shipped
``trialerror/cli/program.py`` through M0-M15 — ``docs/INTEGRATION_NOTES.md``
item 16 named it, ``docs/GETTING_STARTED.md`` §1 documented the workaround
("There is no ``trialerror program init`` command in v0 ... The only piece you
have to create by hand is ``trialerror.toml``"), and 10 other CLI groups'
``program_root_not_found`` refusals pointed ``nextActions`` at a command
that didn't exist. This module closes that gap: ``init`` only (design also
names ``list``/``info``, but v0 has no cross-program registry anywhere —
``platform.db`` scopes rows BY ``program_id``, it doesn't enumerate known
programs — so ``list``/``info`` would need to invent one; TRIALERROR-DEV-NOTE,
left for a v1 ticket alongside ``INTEGRATION_NOTES.md`` item 16 rather than
built speculatively here).

Registration rule (design Section 5.2 / lane safety): this module lives at
``trialerror/cli/program.py`` and is auto-discovered by
``trialerror.cli.discover_groups`` — adding it never touches
``trialerror/cli/__init__.py`` (FX-12, a different fix in this same session,
touches that file for an unrelated, orthogonal reason — see its own
TRIALERROR-DEV-NOTE there).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from trialerror.stores.errors import StoreError
from trialerror.stores.store import open_store
from trialerror.util.envelope import error_envelope, next_action, ok_envelope

GROUP_NAME = "program"
HELP = "Per-program scaffold bootstrap: init (creates trialerror.toml + stores/ + the program layout)."

#: Design Section 3.2's per-program layout, minus `stores/` (created +
#: migrated by `open_store` itself, below) and `.claude/settings.json`
#: (plugin install/MCP-registration is its own step — `docs/OPERATOR_
#: GUIDE.md`'s "Registering the MCP servers" section names the exact
#: `claude mcp add ...` commands; this CLI has no business guessing where
#: the user's TrialError checkout lives to auto-write that file).
_SCAFFOLD_DIRS = ("raw", "archive", "memory", "law", "handoffs", "artifacts", "requests")

_TRIALERROR_TOML_TEMPLATE = """\
# trialerror.toml -- per-program scaffold config (design Section 3.2).
# Generated by `trialerror program init`. Every table below except [program] is
# optional; a field left commented out falls back to its documented
# default -- see docs/GETTING_STARTED.md, docs/OPERATOR_GUIDE.md, and each
# consuming module's own docstring for the full list.

[program]
id = "{program_id}"

# Legacy/typed id-prefix pins (trialerror.util.config.ProgramConfig.id_prefixes)
# -- uncomment to pin a program's own prefix style across a migration.
# [id_prefixes]
# ruling = "C"
# critic_review = "CR"

# Model-policy floor per purpose (design Section 1.11): trialerror.budget.policy
# refuses a book_launch below the configured minimum model_class for a
# purpose (the spawn gate) unless an override_ruling_id is cited. Classes,
# low to high: "small" < "mid" < "top". A purpose not listed here has no
# floor.
# [models]
# keystone = "top"
# ideation = "top"
# mechanical = "small"

# License posture (trialerror.util.config.ProgramConfig.license_posture);
# consulted by trialerror.ingest.pipeline's acquisition-route allowlist.
# [license]
# posture = "internal-research"

# Per-program path overrides (trialerror.util.config.resolve_configured_path /
# configured_path_value) -- relocate any of TrialError's rendered/output
# locations without moving data, e.g. to bridge INTO an existing non-TrialError
# project's own layout instead of restructuring it (see
# plugin/skills/import-existing-project, and docs/the import-design notes (internal, not in this export) for
# the worked example). Every value below is program-root-relative unless
# given as an absolute path; a field left commented out falls back to the
# literal shown. `ingest_roots` (a list) is the one knob that predates this
# table and already worked -- the other six are what this table adds.
# [paths]
# stores_dir = "stores"
# archive_dir = "archive"
# law_digest_path = "law/LAW_DIGEST.md"
# handoffs_dir = "handoffs"
# requests_path = "requests/REQUESTS.md"
# memory_dir = "memory"
# ingest_roots = ["raw", "inbox"]

# OCR backend (trialerror.ingest.backends.load_ocr_backend). Defaults to the
# deterministic FakeOcrBackend (zero-GPU, zero-model) when this table is
# absent -- fine to start with; point at real marker_single once you have
# local GPU tooling set up (docs/USER_SETUP.md).
#
# Absolute paths below must be absolute FOR THE PLATFORM YOU RUN ON --
# `pathlib` decides absoluteness against the host, so a "C:/..." value on
# Linux reads as relative and would be joined onto the program root.
# trialerror.util.config refuses that rather than resolving it somewhere
# surprising; use the line for your own OS.
# [ingest.ocr]
# backend = "marker"
# marker_single_exe = "/opt/marker/bin/marker_single"       # Linux/macOS
# marker_single_exe = "C:/path/to/marker_single.exe"        # Windows
# timeout_s = 900

# Embedding backend (trialerror.ingest.backends.load_embed_backend). Defaults
# to the deterministic FakeEmbedBackend (16-dim, zero-GPU) when this table
# is absent.
# [ingest.embed]
# backend = "qwen3-4b"
# python_exe = "/home/you/research/tools/embeddings_local/venv/bin/python"   # Linux/macOS
# python_exe = "C:/path/to/embeddings_local/venv/Scripts/python.exe"         # Windows
# module_dir = "/home/you/research/tools/embeddings_local"                   # Linux/macOS
# module_dir = "C:/path/to/research/tools/embeddings_local"                  # Windows
# dims = 2048
# timeout_s = 1800

# Literature-metadata API clients (trialerror.litapi.config, `trialerror lit ...`).
# Every field defaults conservatively when this section is absent -- see
# trialerror/litapi/config.py's own module docstring for the exact numbers and
# their provenance.
# [litapi.openalex]
# mailto = "you@example.org"
# api_key_path = ""
# min_interval_s = 1.0
# retry_attempts = 3
# timeout_s = 15.0
#
# [litapi.semanticscholar]
# api_key_path = ""
# min_interval_s = 1.0
# retry_attempts = 5
# timeout_s = 15.0
"""


def register(subparsers: argparse._SubParsersAction) -> argparse.ArgumentParser:
    parser = subparsers.add_parser(GROUP_NAME, help=HELP)
    actions = parser.add_subparsers(dest="action", metavar="<action>")

    p_init = actions.add_parser(
        "init", help="scaffold a new research program: trialerror.toml + the design's per-program layout + migrated stores"
    )
    p_init.add_argument("name", help="the program id, written to trialerror.toml's [program].id")
    p_init.add_argument(
        "--dir", default=None, dest="dir_",
        help="where to create the program root (default: ./<name> under CWD)",
    )
    p_init.add_argument(
        "--platform-root", default=None,
        help="override the platform root the initial migration opens (default: TRIALERROR_PLATFORM_ROOT or ~/.trialerror; "
        "mainly for tests)",
    )
    p_init.set_defaults(handler=_run_init)

    parser.set_defaults(handler=_run_no_action)
    return parser


def _run_no_action(_args: argparse.Namespace) -> dict:
    return error_envelope(
        "program", "no_action", "specify an action: init",
        next_actions=[next_action(["trialerror", "program", "--help"], "list program actions")],
    )


def _run_init(args: argparse.Namespace) -> dict:
    program_root = Path(args.dir_).resolve() if args.dir_ else (Path.cwd() / args.name).resolve()
    trialerror_toml_path = program_root / "trialerror.toml"

    if program_root.is_file():
        return error_envelope(
            "program init", "dir_is_a_file",
            f"{program_root} already exists and is a file, not a directory",
        )
    if trialerror_toml_path.exists():
        return error_envelope(
            "program init", "already_scaffolded",
            f"{trialerror_toml_path} already exists -- program init refuses to overwrite an existing scaffold",
            next_actions=[next_action(["trialerror", "session", "boot"], "boot a session in the existing program")],
        )

    program_root.mkdir(parents=True, exist_ok=True)
    for name in _SCAFFOLD_DIRS:
        (program_root / name).mkdir(parents=True, exist_ok=True)

    trialerror_toml_path.write_text(_TRIALERROR_TOML_TEMPLATE.format(program_id=args.name), encoding="utf-8")

    # Run the initial migration: open_store() creates + migrates all four
    # DBs (platform/ops/knowledge/jobs) for a fresh program_root, per
    # trialerror.stores.migrate.apply_migrations -- the exact "PRAGMA
    # user_version 0 -> latest" bootstrap design Section 3.2 names.
    try:
        store = open_store(program_root, platform_root=Path(args.platform_root) if args.platform_root else None)
    except StoreError as exc:
        return error_envelope("program init", "migration_failed", str(exc), details={"program_root": str(program_root)})
    try:
        stores_dir = store.program_root / "stores"
    finally:
        store.close()

    return ok_envelope(
        "program init",
        result={
            "program_id": args.name,
            "program_root": str(program_root),
            "trialerror_toml": str(trialerror_toml_path),
            "stores_dir": str(stores_dir),
            "scaffolded_dirs": [str(program_root / n) for n in _SCAFFOLD_DIRS],
        },
        next_actions=[
            next_action(
                ["trialerror", "session", "boot", "--create-account", "<label>", "--program-root", str(program_root)],
                "bootstrap the first account and boot the first session",
            ),
            next_action(
                ["trialerror", "doctor", "--program-root", str(program_root)],
                "sanity-check the fresh scaffold",
            ),
        ],
    )
