"""Not a test module (pytest only collects ``test_*.py``) -- the fake
``marker_single`` the page-range chunking suite drives, and the synthetic
PDFs it reads.

**Why a script on disk rather than a stub object.** The thing under test is
an argv: which flag, spelled how, with what value, how many times. A stub
class standing in for the backend would assert that the harness calls itself
the way the harness calls itself. This stub is a real executable, invoked by
the real ``subprocess.run`` in the real backend, and it records every argv it
was given -- so "one invocation per range, each carrying ``--page_range
A-B``" is measured at the only place it can be.

The stub emits marker's paginated markdown: ``{N}`` on its own line followed
by that page's body. **How ``N`` is counted is the stub's central knob**,
because it is the one thing about the real tool that this repo got wrong: it
is the page's own index in the document (``numbering="absolute"``, the
DEFAULT here because it is what marker-pdf 1.10.x actually does under
``--page_range``), or counted from the start of the invocation
(``numbering="relative"``), or -- the case no convention can place --
1-based (``numbering="one_based"``). Every deviation the backend has a
refusal for is a flag on :func:`write_stub_marker`, so each refusal is
driven by a marker that really behaves that way rather than by a monkeypatch.

The body text is always ``body of page <absolute>``, under every convention:
a page whose number and whose content disagree is exactly the failure the
numbering rule exists to prevent, so the fixture makes it visible.

No GPU anywhere: the PDFs are blank pages from ``pypdf`` and the "OCR" is
the stub writing one line per page.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Sequence

__all__ = [
    "A4_PT",
    "A4_LANDSCAPE_PT",
    "POSTER_PT",
    "BOTH_CONVENTIONS",
    "write_stub_marker",
    "stub_argv",
    "make_pdf",
]

#: What every numbering-dependent test is parametrised over. ``absolute``
#: first because it is the supported release's behaviour and therefore the
#: case a regression would be found in.
BOTH_CONVENTIONS = ("absolute", "relative")

#: A4 in PDF points (72 per inch): 8.27 x 11.69 inches. The page size the
#: default budget's arithmetic is stated in.
A4_PT: tuple[float, float] = (595.0, 842.0)

#: The same page turned on its side -- same area, which is the point: a
#: planner that read width alone would size differently for the two.
A4_LANDSCAPE_PT: tuple[float, float] = (842.0, 595.0)

#: A large-format page, four times A4's area. What makes a mixed document
#: plan against its worst page rather than its average one.
POSTER_PT: tuple[float, float] = (1190.0, 1684.0)


#: Substituted with plain replacement rather than ``str.format``/``%``: the
#: script is full of ``{N}`` page markers, and a template language that reads
#: braces would have to escape every one of them.
_STUB_TEMPLATE = '''#!@@PYTHON@@
"""A fake ``marker_single``. Generated by tests/_ocr_range_fixtures.py."""
import json
import sys
from pathlib import Path

FLAG = @@FLAG@@
SUPPORTS_FLAG = @@SUPPORTS_FLAG@@
NUMBERING = @@NUMBERING@@
NUMBERING_BY_RANGE = @@NUMBERING_BY_RANGE@@
MARKER_OFFSET = @@MARKER_OFFSET@@
OMIT_PAGES = @@OMIT_PAGES@@
REVERSED_PAGES = @@REVERSED_PAGES@@
TOTAL_PAGES = @@TOTAL_PAGES@@
LOG = Path(@@LOG@@)
FAIL_ON = @@FAIL_ON@@

HELP = """usage: marker_single [-h] [--output_dir OUTPUT_DIR] [--paginate_output]
                     [--disable_tqdm] [--disable_multiprocessing]"""
if SUPPORTS_FLAG:
    HELP += "\\n                     [" + FLAG + " PAGE_RANGE]"

argv = sys.argv[1:]
if "--help" in argv or "-h" in argv:
    sys.stdout.write(HELP + "\\n")
    raise SystemExit(0)

with LOG.open("a", encoding="utf-8") as handle:
    handle.write(json.dumps(argv) + "\\n")

out_dir = None
page_range = None
positional = []
i = 0
while i < len(argv):
    token = argv[i]
    if token == "--output_dir":
        out_dir = argv[i + 1]
        i += 2
        continue
    if token == FLAG:
        page_range = argv[i + 1]
        i += 2
        continue
    if token.startswith("--"):
        i += 1
        continue
    positional.append(token)
    i += 1

first, last = (0, TOTAL_PAGES - 1)
if page_range:
    first, last = (int(x) for x in page_range.split("-"))
if FAIL_ON is not None and (first, last) == tuple(FAIL_ON):
    sys.stderr.write("stub marker: this range is broken\\n")
    raise SystemExit(3)

convention = NUMBERING_BY_RANGE.get(page_range or "", NUMBERING)

# (marker, absolute page). The BODY always names the absolute page, under
# every convention: a page whose number and whose content disagree is the
# failure the numbering rule exists to prevent, so it has to be visible.
rows = []
for absolute in range(first, last + 1):
    if absolute in OMIT_PAGES:
        # A release that emits nothing at all for a blank page -- no marker,
        # no body. The range then carries less evidence about its own
        # numbering than a full one does.
        continue
    if convention == "absolute":
        marker = absolute
    elif convention == "one_based":
        marker = absolute - first + 1
    else:
        marker = absolute - first
    rows.append((marker + MARKER_OFFSET, absolute))
if REVERSED_PAGES:
    rows = list(reversed(rows))

stem = Path(positional[0]).stem
target = Path(out_dir) / stem
target.mkdir(parents=True, exist_ok=True)
body = []
for marker, absolute in rows:
    body.append("{" + str(marker) + "}" + "-" * 48)
    body.append("body of page " + str(absolute))
    body.append("")
(target / (stem + ".md")).write_text("\\n".join(body), encoding="utf-8")
'''


def write_stub_marker(
    directory: Path,
    *,
    total_pages: int,
    flag: str = "--page_range",
    supports_flag: bool = True,
    numbering: str = "absolute",
    numbering_by_range: dict[str, str] | None = None,
    marker_offset: int = 0,
    omit_pages: Sequence[int] = (),
    reversed_pages: bool = False,
    fail_on: tuple[int, int] | None = None,
) -> Path:
    """Write an executable fake ``marker_single`` and return its path.

    * ``numbering`` -- ``"absolute"`` (the DEFAULT: the ``{N}`` markers carry
      the page's own index in the document, which is what marker-pdf 1.10.x
      does under ``--page_range``), ``"relative"`` (counted from the start of
      the invocation) or ``"one_based"`` (relative but counted from 1, a
      convention no window can place and which therefore has to be refused).
    * ``numbering_by_range={"3-5": "relative"}`` -- that range alone uses
      another convention, so a document can be made to disagree with itself.
    * ``marker_offset`` -- added to every marker, for output that lands
      outside BOTH windows.
    * ``omit_pages`` -- absolute page numbers this release emits nothing at
      all for (no marker, no body), which is how a range is made to carry
      too little evidence to decide its own numbering.
    * ``supports_flag=False`` -- the flag is missing from ``--help``, which is
      the marker release the backend must refuse to chunk with.
    * ``reversed_pages=True`` -- a range's pages come back out of order, so
      the concatenation is not strictly increasing.
    * ``fail_on=(first, last)`` -- that one range exits non-zero, for the
      "one range failed, nothing published" path.

    The log beside it records one JSON array per invocation: read it with
    :func:`stub_argv`.
    """
    if numbering not in ("absolute", "relative", "one_based"):
        raise ValueError(f"unknown stub numbering {numbering!r}")
    directory.mkdir(parents=True, exist_ok=True)
    log = directory / "argv.jsonl"
    script = directory / "marker_single"
    body = _STUB_TEMPLATE
    for token, value in (
        ("@@PYTHON@@", sys.executable),
        ("@@FLAG@@", repr(flag)),
        ("@@SUPPORTS_FLAG@@", repr(bool(supports_flag))),
        ("@@NUMBERING@@", repr(str(numbering))),
        ("@@NUMBERING_BY_RANGE@@", repr(dict(numbering_by_range or {}))),
        ("@@MARKER_OFFSET@@", repr(int(marker_offset))),
        ("@@OMIT_PAGES@@", repr(frozenset(int(p) for p in omit_pages))),
        ("@@REVERSED_PAGES@@", repr(bool(reversed_pages))),
        ("@@TOTAL_PAGES@@", repr(int(total_pages))),
        ("@@LOG@@", repr(str(log))),
        ("@@FAIL_ON@@", repr(list(fail_on) if fail_on is not None else None)),
    ):
        body = body.replace(token, value)
    script.write_text(body, encoding="utf-8", newline="\n")
    script.chmod(0o755)
    return script


def stub_argv(script: Path) -> list[list[str]]:
    """Every argv the stub was invoked with, in order (``--help`` probes are
    not recorded -- they exit before the log is written, which is what makes
    "one invocation per range" countable)."""
    log = script.parent / "argv.jsonl"
    if not log.is_file():
        return []
    return [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines() if line]


def make_pdf(path: Path, sizes: Sequence[tuple[float, float]]) -> Path:
    """A PDF of blank pages with the given ``(width_pt, height_pt)`` boxes.

    Blank because the planner reads the page TREE and nothing else, and the
    OCR of these pages is whatever the stub says it is."""
    from pypdf import PdfWriter

    writer = PdfWriter()
    for width, height in sizes:
        writer.add_blank_page(width=width, height=height)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as handle:
        writer.write(handle)
    return path
