"""The narrative the demo program tells, kept apart from the mechanics that
write it (:mod:`trialerror.demo.seed`).

Everything here is SYNTHETIC and labelled as such. The corpus documents are
written to look structurally like real research notes -- headings, a findings
section, quotable sentences -- because the point is to exercise chunking,
anchoring, retrieval and the license fence against something with realistic
shape. They are not real papers, and they deliberately do not imitate any:
every title carries a ``[DEMO]`` prefix, every body opens by saying it is a
fixture, and the authors are named as the demo generator. A dashboard
screenshot taken from this program should be impossible to mistake for
someone's actual literature.

The subject matter is a plausible research question -- whether interleaved
practice beats blocked practice for motor-skill retention -- chosen because
it produces the things the dashboard needs to look alive: a claim two
sources disagree about, a definition worth pinning in the lexicon, a
methodological objection worth a critique gate, and a question worth freezing
a deliberation room over.
"""

from __future__ import annotations

PROGRAM_QUESTION = (
    "Does interleaved practice produce better long-term motor-skill retention "
    "than blocked practice, and does the effect survive a delayed post-test?"
)

_FIXTURE_BANNER = (
    "> **Synthetic demo fixture.** This document was generated by "
    "`trialerror demo seed` to populate a sample program. It is not a real "
    "paper and reports no real results.\n"
)


def _doc(title: str, body: str) -> str:
    return f"# {title}\n\n{_FIXTURE_BANNER}\n{body}"


#: (filename, source kwargs, markdown body). Ordered so the license-tier and
#: request-state histograms on the corpus panel each get more than one bar --
#: a single-tier corpus renders as one flat block and shows nothing about the
#: fence. ``commercial_restricted`` is present specifically so the retrieval
#: fence (no verbatim run over 20 words) has something to actually fence.
DOCUMENTS: list[tuple[str, dict, str]] = [
    (
        "interleaving-retention.md",
        {
            "kind": "paper",
            "title": "[DEMO] Interleaved Practice and Delayed Retention",
            "license_tier": "open",
            "acquisition_route": "author_posted",
            "authors": "trialerror demo seed (synthetic)",
            "year": 2024,
            "venue": "Synthetic Fixtures in Motor Learning",
        },
        _doc(
            "Interleaved Practice and Delayed Retention",
            "## Background\n\n"
            "Blocked practice groups all repetitions of one skill together before "
            "moving to the next. Interleaved practice alternates between skills "
            "within a single session. Learners consistently rate blocked practice "
            "as more effective while performing worse on delayed tests.\n\n"
            "## Method\n\n"
            "Participants in the synthetic cohort practised three variants of a "
            "throwing task across six sessions, then returned for a delayed "
            "post-test after fourteen days.\n\n"
            "## Findings\n\n"
            "Interleaved practice produced lower accuracy during acquisition but "
            "higher accuracy at the delayed post-test. The advantage at retention "
            "was larger than the deficit during acquisition, which is the pattern "
            "the desirable-difficulties account predicts.\n\n"
            "The subjective ratings inverted the objective result: learners in the "
            "blocked condition were more confident and less accurate.\n",
        ),
    ),
    (
        "blocked-practice-null.md",
        {
            "kind": "paper",
            "title": "[DEMO] A Null Result for Interleaving in Novice Learners",
            "license_tier": "academic_oa",
            "acquisition_route": "publisher_oa",
            "authors": "trialerror demo seed (synthetic)",
            "year": 2025,
            "venue": "Synthetic Fixtures in Motor Learning",
        },
        _doc(
            "A Null Result for Interleaving in Novice Learners",
            "## Background\n\n"
            "The interleaving advantage is often reported without reference to "
            "the learner's starting skill level.\n\n"
            "## Findings\n\n"
            "Among novices with no prior exposure to the task, interleaved and "
            "blocked practice produced statistically indistinguishable retention "
            "at the delayed post-test. The interleaving advantage appeared only in "
            "the subgroup that had already reached a criterion level of "
            "proficiency during acquisition.\n\n"
            "This is the contradiction the demo program's deliberation room is "
            "convened to resolve: the effect may be real but conditional on "
            "baseline proficiency, rather than general.\n",
        ),
    ),
    (
        "desirable-difficulties-primer.md",
        {
            "kind": "book",
            "title": "[DEMO] A Primer on Desirable Difficulties",
            "license_tier": "commercial_restricted",
            "acquisition_route": "user_scan",
            "authors": "trialerror demo seed (synthetic)",
            "year": 2023,
            "rights_notes": (
                "Synthetic fixture standing in for a commercially licensed text: "
                "present so the retrieval fence has a restricted-tier source to "
                "cap verbatim quoting against."
            ),
        },
        _doc(
            "A Primer on Desirable Difficulties",
            "## Definition\n\n"
            "A desirable difficulty is a training condition that slows apparent "
            "progress during acquisition while improving long-term retention and "
            "transfer. The difficulty is desirable precisely because the extra "
            "effort it demands is what produces the durable representation.\n\n"
            "## Scope\n\n"
            "Not every difficulty is desirable. A condition that merely confuses "
            "the learner, or that exceeds what they can process, degrades both "
            "acquisition and retention. The distinction is whether the added "
            "effort is retrieval effort.\n",
        ),
    ),
]

#: Sources registered WITHOUT a delivered document -- these are what make the
#: acquisition queue on the determinations panel non-empty. ``request_state``
#: is the whole point of each row.
PENDING_SOURCES: list[dict] = [
    {
        "kind": "paper",
        "title": "[DEMO] Contextual Interference in Applied Settings",
        "license_tier": "unknown",
        "acquisition_route": "institutional",
        "request_state": "requested",
        "authors": "trialerror demo seed (synthetic)",
    },
    {
        "kind": "report",
        "title": "[DEMO] Coaching Practice Schedules: A Field Survey",
        "license_tier": "unknown",
        "acquisition_route": "user_delivered",
        "request_state": "wanted",
        "authors": "trialerror demo seed (synthetic)",
    },
]

#: Feed posts. ``author`` is derived from the posting launch's agent_kind, and
#: the dashboard renders the text before the first ':' as the post's badge --
#: so posting from several agent kinds is what gives the feed varied badges
#: instead of one repeated chip.
FEED_THREAD_TITLE = "Does the interleaving advantage survive in novices?"

FEED_POSTS: list[tuple[str, str]] = [
    (
        "orchestrator",
        "Opening the thread on the retention question. Two sources now disagree: "
        "the delayed-retention fixture reports a clear interleaving advantage, the "
        "novice-cohort fixture reports a null. Before we treat that as a real "
        "contradiction I want the moderating variable named explicitly.",
    ),
    (
        "lens",
        "Reading both through a measurement lens: the two use different delayed "
        "post-test intervals (14 days vs 7). If the advantage emerges with "
        "consolidation time, a 7-day test could miss it entirely. That is a "
        "cheaper explanation than a genuine boundary condition.",
    ),
    (
        "lens",
        "Reading through a population lens instead: the null result is explicitly "
        "scoped to learners with no prior exposure. The other fixture does not "
        "report baseline proficiency at all, so we cannot rule out that its cohort "
        "was already past the criterion the null paper identifies.",
    ),
    (
        "critic",
        "Both explanations are live and they are not mutually exclusive. What is "
        "not defensible is the current draft's sentence claiming the effect is "
        "'robust across populations' -- neither source supports that, and one "
        "directly contradicts it. Flagging for the gate.",
    ),
]

#: Terms the demo's extraction judge looks for, as
#: ``(term, entity_type, claim_kind)``. These are lifted from the corpus text
#: above, so each one is genuinely present and the sentence containing it can
#: serve as a real grounding anchor. ``definition`` is deliberately over-
#: represented: the lexicon's definitions section inner-joins claims to
#: anchors, so only definition claims with anchors light it up.
EXTRACTION_TERMS: list[tuple[str, str, str]] = [
    ("desirable difficulty", "concept", "definition"),
    ("interleaved practice", "concept", "definition"),
    ("Blocked practice", "concept", "definition"),
    ("delayed post-test", "method", "definition"),
    ("retrieval effort", "mechanism", "mechanism"),
    ("contextual interference", "concept", "definition"),
]

#: How many extraction candidates to leave unreviewed. The review queue is
#: the point of the design's never-silent-auto-merge posture, so it should not
#: be empty in a demo of it.
EXTRACTION_LEFT_PENDING = 3

#: The unread directive on the inbox. One item is enough to light the counter
#: without burying the panel.
INBOX_ITEM = (
    "Before the next ideation round: decide whether baseline proficiency is a "
    "stratification variable or a control. It changes the lens roster."
)

#: The open room's discussion points. Two DPs, because the DP ladder needs
#: more than one rung to read as a ladder.
ROOM_TOPIC = "Is the interleaving advantage conditional on baseline proficiency?"

ROOM_DISCUSSION_POINTS: list[dict] = [
    {
        "prompt": "Is the 7-day vs 14-day post-test interval sufficient to explain "
        "the divergent results on its own?",
    },
    {
        "prompt": "Should baseline proficiency be treated as a moderator to be "
        "measured, or as an inclusion criterion to be controlled?",
    },
]

#: Agreement trajectory per DP, in scoring-round order. The dashboard draws
#: dp_agreement_series from room_dp_scored EVENT rows (room_score itself is an
#: upsert holding one value), so a DP needs at least two rounds to render as a
#: line rather than a dot. The first DP converges past the 90% bar; the second
#: stalls below it, which is what makes the frozen-room path believable.
ROOM_AGREEMENT_SERIES: list[list[float]] = [
    [62.0, 78.0, 91.0],
    [48.0, 55.0, 58.0],
]

ROOM_TURNS: list[tuple[int, str, str]] = [
    (0, "lens", "The interval difference is real but small. Consolidation effects "
        "in this literature are usually reported as emerging within a week, so a "
        "7-day test should already show a partial effect if one exists."),
    (0, "lens", "Agreed that it cannot be the whole story. It could still be "
        "attenuating the effect enough to cross below significance in a "
        "small cohort."),
    (1, "lens", "Measuring it is strictly more informative. Controlling it "
        "throws away the exact variation the disagreement is about."),
    (1, "critic", "Measuring it costs us statistical power we do not have in the "
        "cohorts available. I am not convinced the informativeness argument "
        "survives contact with the sample sizes."),
]

#: The second room, frozen without converging -- this is what puts a
#: room_escalation item (one of only two BLOCKING determination kinds) into
#: the DECIDE queue.
FROZEN_ROOM_TOPIC = "Should the draft's 'robust across populations' claim be retracted outright?"

FROZEN_ROOM_DISCUSSION_POINTS: list[dict] = [
    {"prompt": "Is retraction of the claim the minimum defensible action?"},
]

FROZEN_ROOM_REASON = (
    "Two rounds at 44% and 41% agreement with no movement. The participants are "
    "disagreeing about what the draft is claiming, not about the evidence, so "
    "more rounds will not converge it. Escalating to the operator."
)

#: The critique gate's findings. ``blocking=True`` with no verification is what
#: puts a gate_edit into the DECIDE queue and lights the WARN chip; the
#: non-blocking one is there so the panel shows the distinction.
GATE_EDITS: list[dict] = [
    {
        "blocking": True,
        "text": "The draft claims the interleaving advantage is 'robust across "
        "populations'. One ingested source reports a null result in novices and "
        "explicitly scopes the effect to learners past a proficiency criterion, so "
        "the claim as written is contradicted by the corpus it cites. Replace it "
        "with the conditional form and cite both sources at that sentence.",
    },
    {
        "blocking": False,
        "text": "The methods section does not state the delayed post-test interval, "
        "which is the one variable the two sources demonstrably differ on. State it "
        "explicitly.",
    },
]

#: Course criteria, in narrative order. ``criterion`` has no CLI writer
#: anywhere in the codebase -- see the note in seed.py -- so these are the
#: rows the demo inserts directly. The mix of states is what draws the phase
#: spine with progress rather than an empty ladder.
CRITERIA: list[tuple[str, str, str]] = [
    ("Research question stated in falsifiable form", "framing", "discharged"),
    ("Scope and exclusions written down", "framing", "discharged"),
    ("Corpus covers both sides of the contradiction", "evidence", "discharged"),
    ("Every claim in the draft resolves to an anchor", "evidence", "open"),
    ("Baseline proficiency decided: moderator or control", "evidence", "blocked"),
    ("Methods note passes critique gate", "synthesis", "open"),
    ("Findings draft passes critique gate", "synthesis", "open"),
    ("Delayed post-test interval justified in writing", "synthesis", "open"),
]

#: Memory items. The last two are a deliberate conflict pair -- the merge
#: classifier surfaces them as needs_merge, which is what puts a
#: memory_conflict item in the DECIDE queue.
MEMORY_ITEMS: list[tuple[str, str, str, str]] = [
    (
        "convention/citation-density",
        "L1",
        "rule",
        "Every paragraph making an empirical claim carries at least one anchor. "
        "Paragraphs that only restate prior text do not need one.",
    ),
    (
        "finding/interleaving-conditional",
        "L1",
        "fact",
        "Working position: the interleaving advantage is real but conditional on "
        "baseline proficiency. Not yet gate-approved.",
    ),
    (
        "convention/post-test-interval",
        "L1",
        "rule",
        "Report the delayed post-test interval in days, always, even when the "
        "source leaves it implicit.",
    ),
    (
        "lesson/acquisition-before-drafting",
        "L1",
        "lesson",
        "Resolving a corpus contradiction before drafting saved a rewrite. Worth "
        "repeating: acquire and reconcile, then draft.",
    ),
]

#: The closed session's course check -- ``session.course_check`` is where the
#: course panel's drift log actually comes from.
COURSE_CHECK_CLOSED = {
    "on_course": False,
    "note": "Spent most of the session on corpus acquisition rather than the "
    "drafting the plan called for. Justified -- the contradiction between the two "
    "retention sources was worth resolving first -- but it is a deviation and the "
    "next session should return to drafting.",
}

#: L0 memory abstracts are what the boot bundle injects, so keep them short.
L0_ABSTRACTS = {
    "convention/citation-density": "Anchor every empirical claim.",
    "finding/interleaving-conditional": "Interleaving advantage looks conditional on proficiency.",
    "convention/post-test-interval": "Always report post-test interval in days.",
}
