"""``trialerror.sessions`` — the session lifecycle subsystem. Design Section 2
(subsystem table, row E): "Sessions | ``trialerror/sessions`` | Boot/close
rituals as refusing tools; handoff = rendered view." Design Section 12 (M6
row): "open/close/refusals, account binding at boot, boot bundle, handoff
renderer + supersession notice, course-check."

Generalizes origin-project's boot/close ritual (REQUIREMENTS Section 1.3: "boot = a
tool call that verifies pins, arms watchdog, replays deltas; close = a
tool call that refuses if launches dangle or the digest is stale") into a
structured store + refusing CLI/hook surface, replacing the old "newest
suffixed HANDOFF file + STATE delta" hand-authored convention with a
session row in ``ops.db`` and a handoff file that is a RENDERED VIEW of it
(design Section 3.2/4: never hand-edited, regenerated by the API that
mutates the canonical row).

Public surface:

- :func:`boot_session` — open (or, by default, reuse) the program's one
  OPEN session: resolves/binds the account (F14), stamps the current law
  pin, refuses on a tampered ledger, and returns a boot bundle (pin
  status, foreign rulings since the last session, dangling launches,
  unread inbox, budget headroom, L0 memory, the latest handoff).
- :func:`close_session` — the close ritual's refusal ladder (course-check
  required, hooks armed, no dangling launches, pin not stale, inbox read)
  then: close report, rendered handoff with supersession notice on the
  prior one, ``session_close`` event.
- :func:`evaluate_close_readiness` — the narrower {dangling launches,
  stale pin} check the Stop hook uses (design Section 5.4 Stop row) and
  that :func:`close_session` layers its own extra checks on top of.
- :func:`abandon_session` — mark a crashed/never-closed session
  ``abandoned`` (see module TRIALERROR-DEV-NOTE in ``trialerror.sessions.lifecycle``
  — the design's own ``session.status`` CHECK constraint names this state
  but assigns no module the job of reaching it; M6 owns session lifecycle,
  so M6 provides the one API that can).
- :func:`session_status` — read-only snapshot (no side effects) of the
  open session, if any.
- ``trialerror.sessions.handoff`` — the rendered-view renderer + the
  supersession-notice writer + ``rerender_handoff`` (pure re-flush, no new
  supersession, mirroring ``trialerror.law.service.render_current_digest_to_disk``).

``trialerror/sessions/checks.py`` registers this module's ``trialerror doctor``
checks (``session_multiple_open``, ``session_hook_alive``) by the same
auto-discovery convention every other subsystem uses.
"""

from __future__ import annotations

from trialerror.sessions.handoff import (
    WriteHandoffResult,
    latest_handoff,
    list_handoffs,
    next_handoff_filename,
    render_handoff,
    rerender_handoff,
    write_handoff_with_supersession,
)
from trialerror.sessions.lifecycle import (
    AccountResolution,
    BootResult,
    CloseReadiness,
    CloseResult,
    abandon_session,
    boot_session,
    close_session,
    evaluate_close_readiness,
    resolve_account_for_boot,
    session_status,
)

__all__ = [
    "AccountResolution",
    "BootResult",
    "CloseReadiness",
    "CloseResult",
    "abandon_session",
    "boot_session",
    "close_session",
    "evaluate_close_readiness",
    "resolve_account_for_boot",
    "session_status",
    "WriteHandoffResult",
    "latest_handoff",
    "list_handoffs",
    "next_handoff_filename",
    "render_handoff",
    "rerender_handoff",
    "write_handoff_with_supersession",
]
