"""Handoff rendering. Design Section 3.2 (per-program scaffold):
"``handoffs/`` # rendered session-close views (generated, never
hand-authored)." Design Section 4: "Rendered markdown files (digest,
handoffs, memory, REQUESTS) are **views**: regenerated by the API that
mutates the canonical row, never hand-edited." Design Section 12 (M6 row):
"handoff renderer + supersession notice"; REQUIREMENTS Section 1.3: "NEW
suffixed handoff w/ supersession notice on the old ... never stacked
addenda; older file gets a supersession notice" (memory index convention:
``HANDOFF_<date>.md``, then same-day closes ``HANDOFF_<date>b.md``,
``c`` ... — the base/unsuffixed file is implicitly "a").

:func:`render_handoff` is a PURE function of (session row, close_report,
course_check) — same inputs, byte-identical markdown, mirroring
``trialerror.law.digest.render_digest``'s discipline; this is what makes
"handoff renders from store only" (design Section 12 M6 acceptance
criterion) a checkable property rather than a vibe: a caller that reads
the same stored row twice gets the same file both times, with no hidden
wall-clock or environment input threaded through this function.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

from trialerror.stores import get
from trialerror.util.atomic import atomic_write_text
from trialerror.util.config import resolve_configured_path
from trialerror.util.timeutil import now

__all__ = [
    "HANDOFFS_DIR_NAME",
    "resolve_handoffs_dir",
    "list_handoffs",
    "latest_handoff",
    "next_handoff_filename",
    "render_handoff",
    "WriteHandoffResult",
    "write_handoff_with_supersession",
    "rerender_handoff",
]

#: Design Section 3.2 per-program scaffold: "``handoffs/``".
HANDOFFS_DIR_NAME = "handoffs"

_SUPERSESSION_MARK = "> **SUPERSEDED**"
_DATED_RE = re.compile(r"^HANDOFF_(\d{4}-\d{2}-\d{2})([a-z]?)\.md$")


def resolve_handoffs_dir(program_root: Path, config: Mapping[str, Any] | None = None) -> Path:
    """``[paths].handoffs_dir`` (default :data:`HANDOFFS_DIR_NAME`,
    program-root-relative unless the configured value is absolute) --
    the import-design notes (internal, not in this export) Sec 5 knob #3, and THE fix for the "hardcoded
    twice, independently" drift bug that section flags: this is now the
    ONE function both this module and ``trialerror.sessions.lifecycle`` call,
    where before each had its own separate literal (this module's own
    ``HANDOFFS_DIR_NAME`` constant, and a bare
    ``store.program_root / "handoffs"`` in ``lifecycle._build_bundle``)."""
    return resolve_configured_path(program_root, config, "handoffs_dir", HANDOFFS_DIR_NAME)


def _handoffs_dir(program_root: Path, config: Mapping[str, Any] | None = None) -> Path:
    return resolve_handoffs_dir(program_root, config)


def list_handoffs(handoffs_dir: Path) -> list[Path]:
    """Every ``HANDOFF_*.md`` file in ``handoffs_dir``, sorted so the
    NEWEST sorts last — a plain string sort of the filenames is correct
    here because ISO dates sort lexically and, within one date, ``'.'``
    (the unsuffixed file's next character) sorts before every lowercase
    suffix letter, so ``HANDOFF_2026-08-02.md`` < ``HANDOFF_2026-08-02b.md``
    without any date-parsing logic."""
    handoffs_dir = Path(handoffs_dir)
    if not handoffs_dir.exists():
        return []
    matches = [p for p in handoffs_dir.iterdir() if p.is_file() and _DATED_RE.match(p.name)]
    return sorted(matches, key=lambda p: p.name)


def latest_handoff(handoffs_dir: Path) -> Path | None:
    files = list_handoffs(handoffs_dir)
    return files[-1] if files else None


def next_handoff_filename(handoffs_dir: Path, date_str: str) -> str:
    """The next handoff filename for ``date_str`` (``'YYYY-MM-DD'``): the
    bare ``HANDOFF_<date>.md`` if nothing exists for this date yet, else
    the next unused letter suffix -- ``b`` first (the origin-project convention: the
    unsuffixed file IS the day's first close, implicitly "a"; the first
    SAME-DAY addendum is ``b``, never a redundant ``a``)."""
    handoffs_dir = Path(handoffs_dir)
    existing_letters: list[str] = []
    base = f"HANDOFF_{date_str}.md"
    base_exists = False
    for p in list_handoffs(handoffs_dir):
        m = _DATED_RE.match(p.name)
        if m is None or m.group(1) != date_str:
            continue
        if m.group(2):
            existing_letters.append(m.group(2))
        else:
            base_exists = True
    if not base_exists and not existing_letters:
        return base
    next_letter = chr(ord(max(existing_letters)) + 1) if existing_letters else "b"
    return f"HANDOFF_{date_str}{next_letter}.md"


def _fmt_json_block(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True)


def render_handoff(
    session: Mapping[str, Any],
    *,
    close_report: Mapping[str, Any],
    course_check: Mapping[str, Any],
) -> str:
    """Render the handoff markdown for one closed (or abandoned) session.
    Pure: reads nothing but its own arguments (no store access, no
    ``now()`` call) — see module docstring."""
    lines: list[str] = []
    lines.append(f"# HANDOFF — session {session['session_id']}")
    lines.append("")
    lines.append(
        "This file is a RENDERED VIEW (trialerror.sessions) — never hand-edit it; "
        "the canonical row lives in ops.db's `session` table. A newer "
        "handoff supersedes this one; check `handoffs/` for the latest "
        "file before treating this as current."
    )
    lines.append("")
    lines.append(f"- session_id: {session['session_id']}")
    lines.append(f"- account_id: {session['account_id']}")
    lines.append(f"- status: {session.get('status')}")
    lines.append(f"- opened_ts: {session['opened_ts']}")
    lines.append(f"- closed_ts: {session.get('closed_ts')}")
    lines.append(f"- boot_pin_version: {session.get('boot_pin_version')}")
    lines.append("")
    lines.append("## Close report")
    lines.append("")
    lines.append("```json")
    lines.append(_fmt_json_block(close_report))
    lines.append("```")
    lines.append("")
    lines.append("## Course check")
    lines.append("")
    lines.append("```json")
    lines.append(_fmt_json_block(course_check))
    lines.append("```")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


@dataclass
class WriteHandoffResult:
    filename: str
    path: str
    superseded_path: str | None
    close_report: dict

    def to_dict(self) -> dict:
        return {
            "filename": self.filename,
            "path": self.path,
            "superseded_path": self.superseded_path,
            "close_report": dict(self.close_report),
        }


def _apply_supersession_notice(path: Path, *, superseded_by_filename: str) -> None:
    text = path.read_text(encoding="utf-8")
    if text.startswith(_SUPERSESSION_MARK):
        return  # already marked -- defensive; the normal flow never re-marks a file twice
    notice = (
        f"{_SUPERSESSION_MARK} by `handoffs/{superseded_by_filename}` "
        "— see that file for the current state.\n\n"
    )
    atomic_write_text(path, notice + text)


def write_handoff_with_supersession(
    store,
    *,
    session: Mapping[str, Any],
    close_report: Mapping[str, Any],
    course_check: Mapping[str, Any],
    now_ts: str | None = None,
    config: Mapping[str, Any] | None = None,
) -> WriteHandoffResult:
    """Render + write a NEW suffixed handoff file for ``session`` (design
    Section 12 M6 row) and, if a prior handoff file existed, patch it with
    a supersession notice pointing at the new one — "one SEPARATE suffixed
    file per session close ... never stacked addenda; older file gets a
    supersession notice" (REQUIREMENTS Section 1.3).

    ``close_report`` is enriched with the computed ``handoff_filename``
    BEFORE rendering (and returned enriched) so the file's own close-report
    block and the caller's stored ``session.close_report`` end up
    IDENTICAL — this is what lets :func:`rerender_handoff` reproduce the
    exact same content later from ops.db alone.

    ``config`` (default ``None``, identical to every pre-existing caller's
    behavior) resolves ``[paths].handoffs_dir`` via
    :func:`resolve_handoffs_dir`.
    """
    ts = now_ts or now()
    date_str = ts[:10]
    handoffs_dir = resolve_handoffs_dir(store.program_root, config)
    prior = latest_handoff(handoffs_dir)

    filename = next_handoff_filename(handoffs_dir, date_str)
    enriched_report = dict(close_report)
    enriched_report["handoff_filename"] = filename

    text = render_handoff(session, close_report=enriched_report, course_check=course_check)
    target = handoffs_dir / filename
    atomic_write_text(target, text)

    superseded_path: str | None = None
    if prior is not None and prior.name != filename:
        _apply_supersession_notice(prior, superseded_by_filename=filename)
        superseded_path = str(prior)

    return WriteHandoffResult(
        filename=filename, path=str(target), superseded_path=superseded_path, close_report=enriched_report
    )


def rerender_handoff(
    store, *, session_id: str, config: Mapping[str, Any] | None = None
) -> WriteHandoffResult:
    """Re-render an ALREADY-CLOSED session's handoff to its ORIGINAL
    filename (recorded in ``session.close_report.handoff_filename`` at
    close time) without bumping to a new suffixed file or touching any
    other file's supersession state — the pure "flush the view back to
    disk" recovery op (``trialerror session render-handoff``), mirroring
    ``trialerror.law.service.render_current_digest_to_disk``: the file got
    deleted, or a process died between the DB commit and the file write.

    ``config`` (default ``None``) resolves ``[paths].handoffs_dir`` via
    :func:`resolve_handoffs_dir` — pass the SAME config the original close
    used, or the re-render lands in the wrong (current-default) directory
    for a program whose handoffs_dir was reconfigured since that close.
    """
    session = get(store, "session", pk_column="session_id", pk_value=session_id)
    if session is None:
        raise ValueError(f"no such session: {session_id!r}")
    if not session.get("close_report"):
        raise ValueError(f"session {session_id!r} has no close_report yet (not closed or abandoned)")
    close_report = json.loads(session["close_report"])
    filename = close_report.get("handoff_filename")
    if not filename:
        raise ValueError(
            f"session {session_id!r}'s close_report has no recorded handoff_filename "
            "(it may have been abandoned rather than cleanly closed -- abandonment does not render a handoff)"
        )
    course_check = json.loads(session["course_check"]) if session.get("course_check") else {}

    text = render_handoff(session, close_report=close_report, course_check=course_check)
    target = resolve_handoffs_dir(store.program_root, config) / filename
    atomic_write_text(target, text)
    return WriteHandoffResult(filename=filename, path=str(target), superseded_path=None, close_report=close_report)
