"""Digest rendering. Design Section 3.2: "``law/LAW_DIGEST.md`` # rendered
digest (git-synced; canonical rows live in ops.db)" and Section 4: "Rendered
markdown files (digest, handoffs, memory, REQUESTS) are **views**:
regenerated by the API that mutates the canonical row, never hand-edited."

:func:`render_digest` is a PURE function of (active rulings, version,
generated_ts) -- same inputs always produce the byte-identical markdown
string, which is what makes ``content_sha256`` a meaningful lockstep check:
``trialerror.law.checks`` recomputes this function from the ops.db rows and
compares the hash against both the stored ``law_digest.content_sha256`` AND
the actual on-disk file's hash, catching either a tampered ledger or a
hand-edited file.

Deliberately does NOT embed its own ``content_sha256`` inside the rendered
text (that would make the hash depend on itself). The hash is metadata
about the file, tracked in ``law_digest.content_sha256``; ``trialerror law
digest`` reports it alongside the file, it does not live inside the file.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Mapping, Sequence

__all__ = ["render_digest", "digest_sha256"]


def _load_json_list(raw: Any) -> list[str]:
    if not raw:
        return []
    if isinstance(raw, list):
        return [str(x) for x in raw]
    try:
        parsed = json.loads(raw)
    except (TypeError, ValueError):
        return [str(raw)]
    if isinstance(parsed, list):
        return [str(x) for x in parsed]
    return [str(parsed)]


def _render_one_ruling(row: Mapping[str, Any]) -> str:
    lines: list[str] = []
    lines.append(f"## {row['ruling_id']} — {row['summary']}")
    lines.append("")
    lines.append(f"- ts: {row['ts']}")
    lines.append(f"- status: {row['status']}")
    domains = _load_json_list(row.get("domains"))
    if domains:
        lines.append(f"- domains: {', '.join(domains)}")
    if row.get("supersedes"):
        note = f" ({row['supersedes_note']})" if row.get("supersedes_note") else ""
        lines.append(f"- supersedes: {row['supersedes']}{note}")
    elif row.get("supersedes_note"):
        lines.append(f"- supersedes: {row['supersedes_note']}")
    clauses = _load_json_list(row.get("standing_clauses"))
    if clauses:
        lines.append("- standing clauses:")
        for c in clauses:
            lines.append(f"  - {c}")
    if row.get("verbatim_quote"):
        lines.append(f"- verbatim: \"{row['verbatim_quote']}\"")
    lines.append("")
    return "\n".join(lines)


def render_digest(
    active_rulings: Sequence[Mapping[str, Any]],
    *,
    version: str,
    generated_ts: str,
) -> str:
    """Render the compressed law digest markdown for ``active_rulings``
    (caller supplies them already filtered to ``status='active'`` and
    ordered by append sequence -- this function does not query a store).
    """
    lines: list[str] = []
    lines.append(f"# LAW_DIGEST — {version}")
    lines.append("")
    lines.append(
        f"Generated {generated_ts} from {len(active_rulings)} active ruling(s). "
        "This file is a RENDERED VIEW (trialerror.law) — never hand-edit it; "
        "the canonical rows live in ops.db's `ruling`/`law_digest` tables."
    )
    lines.append("")
    if not active_rulings:
        lines.append("_(no active rulings)_")
        lines.append("")
    for row in active_rulings:
        lines.append(_render_one_ruling(row))
    return "\n".join(lines).rstrip() + "\n"


def digest_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
